package hr.eazework.com.ui.interfaces;

public interface IAction {

	int SPLASH_VIEW = 0;
	int HOME_VIEW = 1;
	int LOGIN_VIEW = 2;
	int HOME_PROFILE_VIEW = 3;
	int ATTANDANCE_CALENDER=4;
	int LEAVE_BALANCE=5;
	int LEAVE_BALANCE_DETAIL=6;
	int CREATE_NEW_LEAVE=7;
	int PAY_SLIP_VIEW=8;
	int PAY_SLIP_VIEW_DOWNLOAD=9;
	int CHANGE_PASSWORD=10;
	int PENDING_APPROVAL=11;
	int VIEW_PAY_SLIP=12;
	int CREATE_EMPLOYEE_VIEW=13;
	int CREATE_LOCATION_VIEW=14;
	int TEAM_MEMBER_LIST=15;
	int TIME_IN=16;
	int TEAM_MEMBER_HISTORY = 17;
	int HISTORY_TRACK_VIEW = 18;
	int TEAM_MEMBER_PROFILE = 19;
	int EDIT_TEAM_MEMBER = 20;
	int EDIT_STORE_VIEW = 21;
	int STORE_LIST_VIEW = 22;
    int ATTANDANCE_HISTORY = 24;
    int APPROVE_SCREEN = 25;
    int MEMBER_APPROVAL = 26;
    int USER_PROFILE = 27;
    int VIEW_DATABASE = 28;
	int EXPENSE_LIST_VIEW=29;
	int ADD_EXPENSE=30;
	int ADD_EXPENSE_CLAIM=31;
	int EXPENSE_HOME=32;
	int ADVANCE_REQUEST=33;
	int ADVANCE_EXPENSE_SUMMARY=34;
	int EXPENSE_CLAIM_SUMMARY=35;
	int EXPENSE_APPROVAL=36;
	int ADVANCE_APPROVAL=37;
	int WORK_FROM_HOME=38;
	int OUTDOOR_DUTY=39;
	int TOUR=40;
	int WORK_FROM_HOME_SUMMARY=41;
	int OUTDOOR_DUTY_SUMMARY=42;
	int TOUR_SUMMARY=43;
	int ATTENDANCE=44;
	int EDIT_EXPENSE_APPROVAL=45;
	int EDIT_ADVANCE_APPROVAL=46;
	int EDITVIEWEXPENSECLAIM=47;
	int VIEW_LEAVE=48;
	int TIME_ATTENDANCE_SUMMARY=49;
	int VIEW_TOUR=50;
	int VIEW_WFH=51;
	int VIEW_OD=52;
	int VIEW_EXPENSE=53;
	int VIEW_ADVANCE=54;
	int RAISE_TICKET=55;
	int RAISE_TICKET_ADV=56;



}
